### ISSUE TITLE
Aplicação não deve guardar estado do banco de dados no repositório de código

### ISSUE THREAD

**Issue by watabr** [dinotales/send_smart#4]
Os dados e a estrutura do banco de dados não deve ser salvo no repositório de código.
Alternativas seriam:
- utilizar processo de migration para recriar estrutura do banco de dados baseados nos migrations feitos anteriormente
- utilizar uma estrutura de banco de dados externa, onde a aplicação só consuma os dados.

**Comment by fujiokarafael** [comment]
Ajuste realizado
