### ISSUE TITLE
Ajustar documentação para refletir os passos de instalação

### ISSUE THREAD

**Issue by watabr** [dinotales/send_smart#6]
Ajustar documentação para refletir os passos de instalação. 

- [x] Retirar instalação do Django (pois já está no requirements.txt)
- [x] Incluir o comando "pip install -r requirements.txt"
- [x] Retirar as dependências do readme.md e fazer um link ao arquivo requirements.txt

Segue também dicas para um bom readme.md:
https://blog.rocketseat.com.br/como-fazer-um-bom-readme/

**Comment by fujiokarafael** [comment]
Ajuste realizados no README
